spring:
  application:
    name: auth-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false # in docker -> true