server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /v3/api-docs/**, /swagger-ui/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**, /v3/api-docs/**, /swagger-ui/**

        - id: borrowing-service
          uri: lb://borrowing-service
          predicates:
            - Path=/api/v1/borrowings/**, /v3/api-docs/**, /swagger-ui/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/