server:
  port: 8082

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: database
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: none
      password: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 19c9d9b02cd1af79106d6e0286d3a8c0b8fdb90772afc31736ef5a31d64aab74
  expiration: 3600000