server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres-borrowing:5432/borrowingdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: borrowing-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

jwt:
  secret: 19c9d9b02cd1af79106d6e0286d3a8c0b8fdb90772afc31736ef5a31d64aab74